apiVersion: v1
kind: Service
metadata:
  name: {{ include "watchman.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "watchman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.port }}
      protocol: TCP
      name: admin
  selector:
    {{- include "watchman.selectorLabels" . | nindent 4 }}
